The following YARA rule aims to identify potential scam content generated by LLMs:
   ```yara
   rule LLM_Scam_Content {
     meta:
       description = "Detects scam content generated by LLMs"
       author = "AI Threat Intelligence"
     strings:
       $a = "investment opportunity" nocase
       $b = "send money" nocase
       $c = "login credentials" nocase
     condition:
       any of them
   }
   ```