<<<<<<< Updated upstream
The following YARA rule aims to identify potential scam content generated by LLMs:
   ```yara
   rule LLM_Scam_Content {
     meta:
       description = "Detects scam content generated by LLMs"
       author = "AI Threat Intelligence"
     strings:
       $a = "investment opportunity" nocase
       $b = "send money" nocase
       $c = "login credentials" nocase
     condition:
       any of them
   }
   ```
=======
rule GPT_56_Cyber_Malicious_Prompt { strings: $a = "generate exploit" $b = "vulnerability scan" condition: any of them }
>>>>>>> Stashed changes
